package at.eg.sprfrm.cmrdqi.model;

import java.util.Date;

import org.apache.ibatis.type.Alias;

@Alias("DqiDefinition")
//TODO to add the definition of the IssueType that is generated by this check
public class DqiDefinition {
	
	private Long id;
	private String name;
	private String code;
	private String description;
	private String area;
	private String group;
	private String subGroup;
	private String executionFrequency;
	private String check;
	private String lastUser;
	private Date insertTime;
	private Date updateTime;
	
	
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getArea() {
		return area;
	}
	public void setArea(String area) {
		this.area = area;
	}
	public String getGroup() {
		return group;
	}
	public void setGroup(String group) {
		this.group = group;
	}
	public String getSubGroup() {
		return subGroup;
	}
	public void setSubGroup(String subGroup) {
		this.subGroup = subGroup;
	}
	public String getExecutionFrequency() {
		return executionFrequency;
	}
	public void setExecutionFrequency(String executionFrequency) {
		this.executionFrequency = executionFrequency;
	}
	public String getCheck() {
		return check;
	}
	public void setCheck(String sql) {
		this.check = sql.trim();
	}
	public String getLastUser() {
		return lastUser;
	}
	public void setLastUser(String lastUser) {
		this.lastUser = lastUser;
	}
	
	public Date getInsertTime() {
		return insertTime;
	}
	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}
	
	public Date getUpdateTime() {
		return updateTime;
	}
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
	
	@Override
	public String toString() {
		return "DqiDefinition [id="+id+", name=" + name + ", code=" + code + "]";
	}
	
	
	
	  

}
