REM INSERTING into O_LDS_META.CMT_CHECK_PARAMETER
SET DEFINE OFF;
--TRUNCATE THE TABLE;
--truncate table CMT_CHECK_PARAMETER;
--LAYER VALID TABLES
Insert into O_LDS_META.CMT_CHECK_PARAMETER (PRM_ID,PRM_TYPE,PRM_KEY,PRM_VALUE,PRM_REFRESH_FLAG,INSERT_TIME,UPDATE_TIME,LAST_USER)
values (seq_checks.nextval,'FIXED','L2_VALID_TABLES','select * from O_LDS_META.CMT_TABLE where layer_name=''L2'' and instr(table_name,''L2_'')=1','N',sysdate,sysdate,'CMR_CHECK');
Insert into O_LDS_META.CMT_CHECK_PARAMETER (PRM_ID,PRM_TYPE,PRM_KEY,PRM_VALUE,PRM_REFRESH_FLAG,INSERT_TIME,UPDATE_TIME,LAST_USER)
values (seq_checks.nextval,'FIXED','L1_VALID_TABLES','select * from O_LDS_META.CMT_TABLE where layer_name=''L1'' and instr(table_name,''L1_'')=1','N',sysdate,sysdate,'CMR_CHECK');
Insert into O_LDS_META.CMT_CHECK_PARAMETER (PRM_ID,PRM_TYPE,PRM_KEY,PRM_VALUE,PRM_REFRESH_FLAG,INSERT_TIME,UPDATE_TIME,LAST_USER)
values (seq_checks.nextval,'FIXED','BASE_VALID_TABLES','select * from O_LDS_META.CMT_TABLE where layer_name=''BASE'' and instr(table_name,''LC_'')=1','N',sysdate,sysdate,'CMR_CHECK');
--LAYER INVALID TABLES
Insert into O_LDS_META.CMT_CHECK_PARAMETER (PRM_ID,PRM_TYPE,PRM_KEY,PRM_VALUE,PRM_REFRESH_FLAG,INSERT_TIME,UPDATE_TIME,LAST_USER)
values (seq_checks.nextval,'FIXED','L2_NONVALID_TABLES','select * from O_LDS_META.CMT_TABLE where layer_name=''L2'' and instr(table_name,''L2_'')<>1','N',sysdate,sysdate,'CMR_CHECK');
Insert into O_LDS_META.CMT_CHECK_PARAMETER (PRM_ID,PRM_TYPE,PRM_KEY,PRM_VALUE,PRM_REFRESH_FLAG,INSERT_TIME,UPDATE_TIME,LAST_USER)
values (seq_checks.nextval,'FIXED','L1_NONVALID_TABLES','select * from O_LDS_META.CMT_TABLE where layer_name=''L1'' and instr(table_name,''L1_'')<>1','N',sysdate,sysdate,'CMR_CHECK');
Insert into O_LDS_META.CMT_CHECK_PARAMETER (PRM_ID,PRM_TYPE,PRM_KEY,PRM_VALUE,PRM_REFRESH_FLAG,INSERT_TIME,UPDATE_TIME,LAST_USER)
values (seq_checks.nextval,'FIXED','BASE_NONVALID_TABLES','select * from O_LDS_META.CMT_TABLE where layer_name=''BASE'' and instr(table_name,''LC_'')<>1','N',sysdate,sysdate,'CMR_CHECK');

--LAYER PREFIXES
Insert into O_LDS_META.CMT_CHECK_PARAMETER (PRM_ID,PRM_TYPE,PRM_KEY,PRM_VALUE,PRM_REFRESH_FLAG,INSERT_TIME,UPDATE_TIME,LAST_USER)
values (seq_checks.nextval,'FIXED','L1_PREFIX','L1_','N',sysdate,sysdate,'CMR_CHECK');
Insert into O_LDS_META.CMT_CHECK_PARAMETER (PRM_ID,PRM_TYPE,PRM_KEY,PRM_VALUE,PRM_REFRESH_FLAG,INSERT_TIME,UPDATE_TIME,LAST_USER)
values (seq_checks.nextval,'FIXED','BASE_PREFIX','LC_','N',sysdate,sysdate,'CMR_CHECK');
Insert into O_LDS_META.CMT_CHECK_PARAMETER (PRM_ID,PRM_TYPE,PRM_KEY,PRM_VALUE,PRM_REFRESH_FLAG,INSERT_TIME,UPDATE_TIME,LAST_USER)
values (seq_checks.nextval,'FIXED','L2_PREFIX','L2_','N',sysdate,sysdate,'CMR_CHECK');
Insert into O_LDS_META.CMT_CHECK_PARAMETER (PRM_ID,PRM_TYPE,PRM_KEY,PRM_VALUE,PRM_REFRESH_FLAG,INSERT_TIME,UPDATE_TIME,LAST_USER)
values (seq_checks.nextval,'FIXED','SC_PREFIX','ST_','N',sysdate,sysdate,'CMR_CHECK');
Insert into O_LDS_META.CMT_CHECK_PARAMETER (PRM_ID,PRM_TYPE,PRM_KEY,PRM_VALUE,PRM_REFRESH_FLAG,INSERT_TIME,UPDATE_TIME,LAST_USER)
values (seq_checks.nextval,'FIXED','SS_PREFIX','ST_','N',sysdate,sysdate,'CMR_CHECK');
--LAYER NAMES
Insert into O_LDS_META.CMT_CHECK_PARAMETER (PRM_ID,PRM_TYPE,PRM_KEY,PRM_VALUE,PRM_REFRESH_FLAG,INSERT_TIME,UPDATE_TIME,LAST_USER)
values (seq_checks.nextval,'FIXED','L1_LAYER_NAME','L1','N',sysdate,sysdate,'CMR_CHECK');
Insert into O_LDS_META.CMT_CHECK_PARAMETER (PRM_ID,PRM_TYPE,PRM_KEY,PRM_VALUE,PRM_REFRESH_FLAG,INSERT_TIME,UPDATE_TIME,LAST_USER)
values (seq_checks.nextval,'FIXED','L2_LAYER_NAME','L2','N',sysdate,sysdate,'CMR_CHECK');
Insert into O_LDS_META.CMT_CHECK_PARAMETER (PRM_ID,PRM_TYPE,PRM_KEY,PRM_VALUE,PRM_REFRESH_FLAG,INSERT_TIME,UPDATE_TIME,LAST_USER)
values (seq_checks.nextval,'FIXED','BASE_LAYER_NAME','BASE','N',sysdate,sysdate,'CMR_CHECK');
Insert into O_LDS_META.CMT_CHECK_PARAMETER (PRM_ID,PRM_TYPE,PRM_KEY,PRM_VALUE,PRM_REFRESH_FLAG,INSERT_TIME,UPDATE_TIME,LAST_USER)
values (seq_checks.nextval,'FIXED','SC_LAYER_NAME','STAGE CORE','N',sysdate,sysdate,'CMR_CHECK');
Insert into O_LDS_META.CMT_CHECK_PARAMETER (PRM_ID,PRM_TYPE,PRM_KEY,PRM_VALUE,PRM_REFRESH_FLAG,INSERT_TIME,UPDATE_TIME,LAST_USER)
values (seq_checks.nextval,'FIXED','C_LAYER_NAME','CORE','N',sysdate,sysdate,'CMR_CHECK');
Insert into O_LDS_META.CMT_CHECK_PARAMETER (PRM_ID,PRM_TYPE,PRM_KEY,PRM_VALUE,PRM_REFRESH_FLAG,INSERT_TIME,UPDATE_TIME,LAST_USER)
values (seq_checks.nextval,'FIXED','SS_LAYER_NAME','STAGE SEMANTIC','N',sysdate,sysdate,'CMR_CHECK');
Insert into O_LDS_META.CMT_CHECK_PARAMETER (PRM_ID,PRM_TYPE,PRM_KEY,PRM_VALUE,PRM_REFRESH_FLAG,INSERT_TIME,UPDATE_TIME,LAST_USER)
values (seq_checks.nextval,'FIXED','SEMANTIC_LAYER_NAME','SEMANTIC','N',sysdate,sysdate,'CMR_CHECK');